### PR TITLE
semi working player selection

### PR DESCRIPTION
**Pull request by Mokimbo**
got player selection to a usable state. Boxes should pop up on asteroids and planets for now

### CODE REVIEW

**Comment by Mokimbo** [comment]
picking the planet requires you to be really close to it. Need to find a fix so that the selection detection works on the outer ring of the planet as opposed to finding the center of whatever your trying to select.

**Comment by Mokimbo** [comment]
resized the nodes in planet to scale 1 with the sprite being smaller so detection of the planet is more reliable. Removed some old radius variables that were used in testing earlier detection methods. All in all you should be able to detect the planet a lot more reliably.

**Comment by Mokimbo** [comment]
got rid of the planet script for now since there is nothing inside of it we need for now.

**Review by alarner — APPROVED** [review]
Looks good!

**Pull request merged**
